### ISSUE TITLE
httpredir discontinued

### ISSUE THREAD

**Issue by anechampenois** [SolydXK/updatemanager#2]
As this service is now 'deprecated', it seems better  to use deb.debian.org.
Source here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817155

**Comment by ArjenBalfoort** [comment]
We will do that for the next Stretch ISOs. For the time being we're OK as Debian is redirecting httpredir to deb.debian.org.

**Comment by anechampenois** [comment]
Ok  Arjen, I'll inform you if there's no more redirection.
