### ISSUE TITLE
Debian mirrors speed measure doensn't work anymore

### ISSUE THREAD

**Issue by anechampenois** [SolydXK/updatemanager#3]
When using the test for the debian's repositories mirrors' speed, UM gives me  0 to 2 kb/s for each one. The speed seems correct for Solyd's repositories.
UM continues to warn for Debian updates, and is taking  cake of them with a decend bandwidth for uploading.

**Comment by ArjenBalfoort** [comment]
Thanks for the bug report.

Updatemanager is going to be discontinued when Stretch becomes stable. The selection of repositories is going to be implemented in a new GUI for solydxk-system. As this is not a critical issue, I will address this issue in solydxk-system only.

**Comment by anechampenois** [comment]
Ok. I'll test it when the new GUI will be ready.
